export interface RoleDefinition {
  name: string;
  description: string;
  permissions: Array<{ module: string; action: string }>;
}

export const ALL_MODULES = [
  'leads',
  'opportunities',
  'companies',
  'contacts',
  'customers',
  'requirements',
  'activities',
  'followups',
  'documents',
  'tags',
  'settings',
  'users',
  'audit',
  'invoices',
  'payments',
  'expenses',
  'tickets',
  'projects',
];

export const ALL_ACTIONS = ['view', 'create', 'edit', 'delete', 'approve'];

export const DEFAULT_ROLES: RoleDefinition[] = [
  {
    name: 'Super Admin',
    description: 'Full administrative access across all system modules and settings',
    permissions: ALL_MODULES.flatMap((mod) =>
      ALL_ACTIONS.map((act) => ({ module: mod, action: act })),
    ),
  },
  {
    name: 'Admin',
    description: 'Administrative access across all modules except system governance',
    permissions: ALL_MODULES.filter((m) => m !== 'audit').flatMap((mod) =>
      ['view', 'create', 'edit', 'delete'].map((act) => ({ module: mod, action: act })),
    ),
  },
  {
    name: 'Sales Manager',
    description: 'Manages sales pipelines, leads, opportunities, and team activities',
    permissions: [
      { module: 'leads', action: 'view' },
      { module: 'leads', action: 'create' },
      { module: 'leads', action: 'edit' },
      { module: 'leads', action: 'delete' },
      { module: 'opportunities', action: 'view' },
      { module: 'opportunities', action: 'create' },
      { module: 'opportunities', action: 'edit' },
      { module: 'opportunities', action: 'delete' },
      { module: 'companies', action: 'view' },
      { module: 'companies', action: 'create' },
      { module: 'companies', action: 'edit' },
      { module: 'contacts', action: 'view' },
      { module: 'contacts', action: 'create' },
      { module: 'contacts', action: 'edit' },
      { module: 'customers', action: 'view' },
      { module: 'requirements', action: 'view' },
      { module: 'requirements', action: 'create' },
      { module: 'requirements', action: 'edit' },
      { module: 'activities', action: 'view' },
      { module: 'activities', action: 'create' },
      { module: 'activities', action: 'edit' },
      { module: 'followups', action: 'view' },
      { module: 'followups', action: 'create' },
      { module: 'followups', action: 'edit' },
      { module: 'documents', action: 'view' },
      { module: 'documents', action: 'create' },
      { module: 'tags', action: 'view' },
      { module: 'tags', action: 'create' },
    ],
  },
  {
    name: 'Sales Rep',
    description: 'Manages assigned leads, opportunities, and daily sales activities',
    permissions: [
      { module: 'leads', action: 'view' },
      { module: 'leads', action: 'create' },
      { module: 'leads', action: 'edit' },
      { module: 'opportunities', action: 'view' },
      { module: 'opportunities', action: 'create' },
      { module: 'opportunities', action: 'edit' },
      { module: 'companies', action: 'view' },
      { module: 'contacts', action: 'view' },
      { module: 'contacts', action: 'create' },
      { module: 'requirements', action: 'view' },
      { module: 'activities', action: 'view' },
      { module: 'activities', action: 'create' },
      { module: 'followups', action: 'view' },
      { module: 'followups', action: 'create' },
      { module: 'documents', action: 'view' },
    ],
  },
  {
    name: 'Account Manager',
    description: 'Manages customer relationships, contacts, and account onboarding',
    permissions: [
      { module: 'customers', action: 'view' },
      { module: 'customers', action: 'create' },
      { module: 'customers', action: 'edit' },
      { module: 'companies', action: 'view' },
      { module: 'companies', action: 'create' },
      { module: 'companies', action: 'edit' },
      { module: 'contacts', action: 'view' },
      { module: 'contacts', action: 'create' },
      { module: 'contacts', action: 'edit' },
      { module: 'opportunities', action: 'view' },
      { module: 'activities', action: 'view' },
      { module: 'activities', action: 'create' },
      { module: 'followups', action: 'view' },
      { module: 'followups', action: 'create' },
      { module: 'documents', action: 'view' },
      { module: 'documents', action: 'create' },
    ],
  },
  {
    name: 'Finance',
    description: 'Manages invoices, payments, expenses, and financial approvals',
    permissions: [
      { module: 'invoices', action: 'view' },
      { module: 'invoices', action: 'create' },
      { module: 'invoices', action: 'edit' },
      { module: 'payments', action: 'view' },
      { module: 'payments', action: 'create' },
      { module: 'payments', action: 'approve' },
      { module: 'expenses', action: 'view' },
      { module: 'expenses', action: 'create' },
      { module: 'expenses', action: 'approve' },
      { module: 'customers', action: 'view' },
      { module: 'companies', action: 'view' },
    ],
  },
  {
    name: 'Support',
    description: 'Handles support tickets and customer assistance requests',
    permissions: [
      { module: 'tickets', action: 'view' },
      { module: 'tickets', action: 'create' },
      { module: 'tickets', action: 'edit' },
      { module: 'customers', action: 'view' },
      { module: 'companies', action: 'view' },
      { module: 'contacts', action: 'view' },
      { module: 'activities', action: 'view' },
      { module: 'activities', action: 'create' },
    ],
  },
  {
    name: 'Operations',
    description: 'Monitors project delivery, task execution, and cloud resources',
    permissions: [
      { module: 'projects', action: 'view' },
      { module: 'projects', action: 'create' },
      { module: 'projects', action: 'edit' },
      { module: 'customers', action: 'view' },
      { module: 'requirements', action: 'view' },
      { module: 'documents', action: 'view' },
    ],
  },
];
